// GENERATED FILE — do not edit by hand.
// Source: server/src/lib.rs's `ApiDoc` (utoipa) -> dump_openapi -> openapi-typescript.
// Regenerate: dev-tools/gen-api-types.sh
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/allowlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The grants, newest first. */
        get: operations["listAllowlist"];
        put?: never;
        /** Grant (upsert) — the stored row comes back; usernames are canonicalised here. */
        post: operations["grantAllowlist"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/allowlist/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke — 204 on removal, 404 when the grant never existed. */
        delete: operations["revokeAllowlist"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/content-editors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The grants, newest first. */
        get: operations["listContentEditors"];
        put?: never;
        /** Grant (upsert) — the stored row comes back; usernames are canonicalised here. */
        post: operations["grantContentEditor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/content-editors/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke — 204 on removal, 404 when the grant never existed. Change requests the person already
         *     opened are untouched: those live on the forge, and closing them is a reviewer's call.
         */
        delete: operations["revokeContentEditor"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/lesson-views": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Most-read lessons first. What is NOT here is as important as what is: no reader, no session,
         *     no IP — the store cannot answer "who read this" because it never recorded it.
         */
        get: operations["listLessonViews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The frontend's Keycloak coordinates, split from the issuer. */
        get: operations["getAuthConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The listing, newest first (undated last). */
        get: operations["listBlogPosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blog/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One post with body + publish-order neighbours. */
        get: operations["getBlogPost"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/edits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's own change requests, newest first. */
        get: operations["listMyEdits"];
        put?: never;
        /**
         * Propose the edit: commit to this contributor's branch for this page and open (or reuse) a pull
         *     request.
         */
        post: operations["proposeEdit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/edits/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Whether this deployment offers editing, and whether THIS caller may use it. Answers for
         *     everyone — an anonymous reader gets `canEdit: false`, not a 401, because the lesson page asks
         *     this before it knows who is reading.
         */
        get: operations["getEditConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/edits/source/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The lesson's file, whole — frontmatter fence included, because that is what gets committed. */
        get: operations["getEditSource"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness check — 200 while the server is up. Point the orchestrator's `livenessProbe` HERE,
         *     never at `/api/ready`: this one must keep answering while a dependency wobbles, or a restart
         *     storm replaces a recoverable outage with an unrecoverable one.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who am I — the verified caller's echo. */
        get: operations["getMe"];
        put?: never;
        post?: never;
        /**
         * Delete the caller's sign-in: verified bearer required; the Keycloak
         *     call rides the SCOPED service-account client. Failures are loud — never a swallowed
         *     success.
         */
        delete: operations["deleteMe"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The caller's completed lesson paths — private: anonymous callers get `[]` and the store is
         *     never touched (mirrors `list_submissions`).
         */
        get: operations["listProgress"];
        put?: never;
        /**
         * Mark one lesson complete for the caller (idempotent), then return the caller's full completed
         *     list so the client has an authoritative post-mark snapshot. Bearer required.
         */
        post: operations["markProgress"];
        /**
         * Reset all of the caller's progress ("reset progress"). Clears only these rows — the caller's
         *     submission history is a separate store and survives.
         */
        delete: operations["resetProgress"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness check — 200 when the backing store answers, 503 when it does not, so the
         *     orchestrator stops routing traffic to an instance that cannot serve it. The failure reason
         *     goes to the log ONLY; the body stays generic because store errors name hosts and usernames.
         */
        get: operations["getReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run one snippet in the sandbox. */
        post: operations["runCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The caller's OWN submissions for a lesson, newest first — private: anonymous callers get
         *     `[]` and the store is never touched.
         */
        get: operations["listSubmissions"];
        put?: never;
        /** Submit a solution — stored and judged in the background; poll the returned id. */
        post: operations["submitSolution"];
        /** Erase every submission of the caller ("reset my data"). */
        delete: operations["eraseSubmissions"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll one submission (public — ids are unguessable UUIDs). */
        get: operations["getSubmission"];
        put?: never;
        post?: never;
        /** Owner-only delete. */
        delete: operations["deleteSubmission"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/synapse/c4-doc/{element_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A LikeC4 component's tutorial doc, looked up next to the given lesson. */
        get: operations["getComponentDoc"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/synapse/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The browsable library index. */
        get: operations["getSynapseIndex"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/synapse/{paths}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A lesson by its full directory-mirror path (the catch-all — registered least specific). */
        get: operations["getSynapseLesson"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tutor/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** One coaching turn — the full transcript comes up, one reply goes back. */
        post: operations["tutorChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tutor/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The coach's coordinates — answers whether the coach is on or off. */
        get: operations["getTutorConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description One allowlist grant (`/api/admin/allowlist`). */
        AllowlistEntryDto: {
            /** @description ISO-8601 instant. */
            grantedAt: string;
            note?: string | null;
            username: string;
        };
        /**
         * @description The shared error envelope, reused by every context's endpoints. `detail` carries a longer
         *     message; `hint` (optional) is operator-facing (e.g. an env var to set).
         */
        ApiError: {
            detail?: string | null;
            /** @example Not found */
            error: string;
            /** @example Set SYNAPSE_ROOT */
            hint?: string | null;
        };
        /**
         * @description One declared stdin argument. The authored JSON writes `type`; the field is `tpe` here
         *     (mapped at the codec) since `type` is a reserved word.
         */
        ArgSpec: {
            id: string;
            label: string;
            placeholder?: string | null;
            type: string;
        };
        /**
         * @description The SPA's Keycloak coordinates (`GET /api/auth/config`) — exactly
         *     `new Keycloak({url, realm, clientId})`.
         */
        AuthConfigDto: {
            clientId: string;
            realm: string;
            url: string;
        };
        /**
         * @description One post: the summary fields + the markdown body + publish-order neighbours
         *     (`prev` = older, `next` = newer; null at the ends).
         */
        BlogPostDto: {
            body: string;
            eyebrow?: string | null;
            next?: string | null;
            prev?: string | null;
            publishedAt: string;
            /** Format: int32 */
            readMinutes?: number | null;
            slug: string;
            summary?: string | null;
            tags: string[];
            title: string;
        };
        BlogSummaryDto: {
            eyebrow?: string | null;
            publishedAt: string;
            /** Format: int32 */
            readMinutes?: number | null;
            slug: string;
            summary?: string | null;
            tags: string[];
            title: string;
        };
        BookDto: {
            categoryPath: string[];
            description: string;
            entries: components["schemas"]["BookEntryDto"][];
            /** Format: int32 */
            estimatedReadingMinutes?: number | null;
            /** Format: int32 */
            order?: number | null;
            slug: string;
            tags: string[];
            title: string;
        };
        BookEntryDto: (components["schemas"]["ChapterDto"] & {
            /** @enum {string} */
            kind: "chapter";
        }) | (components["schemas"]["LessonDto"] & {
            /** @enum {string} */
            kind: "lesson";
        });
        BookRefDto: {
            categoryPath: string[];
            slug: string;
            title: string;
        };
        CatalogEntryDto: (components["schemas"]["CategoryDto"] & {
            /** @enum {string} */
            kind: "category";
        }) | (components["schemas"]["BookDto"] & {
            /** @enum {string} */
            kind: "book";
        });
        CategoryDto: {
            description?: string | null;
            entries: components["schemas"]["CatalogEntryDto"][];
            icon?: string | null;
            /** Format: int32 */
            order?: number | null;
            slug: string;
            title: string;
        };
        ChapterDto: {
            entries: components["schemas"]["BookEntryDto"][];
            /** Format: int32 */
            order?: number | null;
            slug: string;
            title: string;
        };
        /** @description One chat turn. `role` is `"user" | "assistant"` (the server prepends its own system turn). */
        ChatMessage: {
            content: string;
            role: string;
        };
        ComponentDocDto: {
            body: string;
            kind?: string | null;
            technology?: string | null;
            title?: string | null;
        };
        /** @description Delete/erase result — 0/1 for a single delete, N for erase-all. */
        DeleteResultDto: {
            deleted: number;
        };
        /**
         * @description `GET /api/edits/config` — always answers, even when editing is off, so the client has one
         *     place to ask instead of inferring capability from a 404.
         */
        EditConfigDto: {
            /** @description The branch pull requests target. */
            baseBranch: string;
            /**
             * @description Whether THIS caller may propose edits — signed in and on the content-editor allowlist.
             *     UX only; every write re-checks server-side.
             */
            canEdit: boolean;
            /** @description `false` when the deployment has no forge configured — the editor never offers itself. */
            enabled: boolean;
            /**
             * @description `"github"` (real pull requests) or `"dry-run"` (nothing leaves the process). The editor
             *     says which, plainly, rather than letting a contributor believe a dry run shipped.
             */
            mode: string;
            /** @description `owner/name` of the content repository. */
            repo: string;
        };
        /** @description One proposed change, as stored — the `POST` answer and the rows behind "My change requests". */
        EditRequestDto: {
            branch: string;
            /**
             * Format: int32
             * @description How many commits this branch has carried — 2+ means the contributor revised an open
             *     proposal rather than opening a second one.
             */
            commits: number;
            /** @description ISO-8601 instants. */
            createdAt: string;
            filePath: string;
            id: string;
            lessonPath: string;
            /** @description The forge that handled it (`"github"` / `"dry-run"`), so the result copy can be honest. */
            mode: string;
            /**
             * Format: int64
             * @description Absent on a dry run — nothing was opened.
             */
            prNumber?: number | null;
            prUrl?: string | null;
            /** @description `true` when this submission landed on an ALREADY-OPEN pull request. */
            reused: boolean;
            /** @description `"open" | "merged" | "closed"`. */
            state: string;
            updatedAt: string;
        };
        /** @description `GET /api/edits/source/{*path}` — the file as it is on disk RIGHT NOW. */
        EditSourceDto: {
            /** @description The content checkout's version (git SHA in prod) — shown as provenance. */
            contentVersion: string;
            /**
             * @description The path INSIDE the content repository — real folders carry `NN-` order prefixes, so this
             *     is never derivable from `lesson_path` by the client.
             */
            filePath: string;
            /**
             * @description A digest of `source` the client hands back on submit, so an edit against a stale copy is
             *     refused instead of silently overwriting whatever landed in between.
             */
            fingerprint: string;
            /** @description The URL path (`category…/book/chapter…/lesson`). */
            lessonPath: string;
            /**
             * @description The WHOLE file, frontmatter fence included. Editing the reader's stripped body would
             *     delete the frontmatter on save.
             */
            source: string;
        };
        FailedCaseDto: {
            args: {
                [key: string]: string;
            };
            expected?: string | null;
            index: number;
            runStatus: string;
            stderr: string;
            stdout: string;
        };
        /**
         * @description The grant request — username is trimmed + lowercased server-side (canonical, matching the
         *     verifier); blank is a 400.
         */
        GrantRequestDto: {
            note?: string | null;
            username: string;
        };
        /**
         * @description Walking-skeleton health — just a status string today. Real backing-store checks
         *     (Postgres / go-judge / Keycloak) join it when those stores are actually wired; the spec
         *     grows to match.
         */
        HealthStatus: {
            /** @example ok */
            status: string;
        };
        LessonDto: {
            essential: boolean;
            /**
             * @description The lesson's frontmatter `kind`, index-side, so the client can tell a problem from prose
             *     without fetching every payload (drives the "PROBLEM N / M" counter).
             *
             *     NOT named `kind`: `BookEntryDto` is `#[serde(tag = "kind")]`, so a field by that name
             *     would emit the key TWICE — and serde cannot see inside the newtype to catch it. Skipped
             *     when absent, so prose lessons add nothing to a document every visitor downloads.
             */
            lessonKind?: string | null;
            /** Format: int32 */
            order?: number | null;
            slug: string;
            title: string;
        };
        LessonFrontmatterDto: {
            difficulty?: string | null;
            essential?: boolean | null;
            kind?: string | null;
            summary?: string | null;
            title: string;
            topics?: string[] | null;
        };
        /**
         * @description The lesson the reader renders. `raw` = the markdown body, fence stripped; `prev`/`next` are
         *     ready-to-navigate FULL paths (`category…/book/chapter…/lesson`), null at book ends. `tests`
         *     carries ONLY the sample cases for a `kind: problem` lesson (the workbench sources them from
         *     here now that the description markdown no longer duplicates a `testcases` fence); null otherwise.
         */
        LessonPayloadDto: {
            book: components["schemas"]["BookRefDto"];
            editorial?: string | null;
            frontmatter: components["schemas"]["LessonFrontmatterDto"];
            lesson: components["schemas"]["LessonDto"];
            next?: string | null;
            prev?: string | null;
            raw: string;
            tests?: null | components["schemas"]["TestSpec"];
        };
        /**
         * @description One lesson's readership. `lastViewed` is an ISO-8601 UTC string, matching the `publishedAt`
         *     convention in `blog` — the wire carries strings, the caller parses if it cares.
         */
        LessonViewDto: {
            /** Format: int64 */
            authedViews: number;
            lastViewed: string;
            lessonPath: string;
            /** Format: int64 */
            views: number;
        };
        /** @description `POST /api/progress` body — mark one lesson path complete for the caller. */
        MarkProgressRequestDto: {
            path: string;
        };
        /**
         * @description The verified caller (`GET /api/me`). `admin` is UX-only — the server re-checks per call
         *     against the admin allowlist, so this is only ever a display hint.
         */
        MeDto: {
            admin: boolean;
            email?: string | null;
            id: string;
            username: string;
        };
        /** @description `GET /api/progress` — every lesson path the caller has completed. */
        ProgressListDto: {
            completed: string[];
        };
        /** @description `POST /api/edits` body. */
        ProposeEditRequestDto: {
            /** @description The `fingerprint` that came with the source this edit started from. */
            baseFingerprint: string;
            lessonPath: string;
            /** @description The proposed file, whole. */
            source: string;
            /** @description The contributor's own words — becomes the commit message body and the pull-request body. */
            summary?: string | null;
        };
        /** @description The run request. `language` is a fence alias (`py`, `cpp`, …), resolved server-side. */
        RunRequest: {
            language: string;
            source: string;
            stdin?: string | null;
        };
        /** @description The run's outcome. `time_seconds`/`memory_kb` are absent when the backend didn't measure. */
        RunResult: {
            compileOutput: string;
            /** Format: int64 */
            memoryKb?: number | null;
            status: components["schemas"]["RunStatus"];
            stderr: string;
            stdout: string;
            /** Format: double */
            timeSeconds?: number | null;
        };
        /**
         * @description What a run produced, as vocabulary. A badly-running program is still a 200 with a
         *     non-`Accepted` status — only backend machinery failures use the error channel.
         * @enum {string}
         */
        RunStatus: "Accepted" | "CompileError" | "RuntimeError" | "TimeLimitExceeded" | "InternalError";
        /** @description The 202 body — poll `GET /api/submissions/{id}` until `status == "completed"`. */
        SubmissionAcceptedDto: {
            id: string;
        };
        SubmissionDto: {
            completedAt?: string | null;
            /** @description ISO-8601 instant. */
            createdAt: string;
            /** @description The `judge-failed` machinery message only. */
            detail?: string | null;
            firstFailure?: null | components["schemas"]["FailedCaseDto"];
            id: string;
            language: string;
            passed?: number | null;
            path: string[];
            source: string;
            /** @description `"pending" | "judging" | "completed"`. */
            status: string;
            total?: number | null;
            /** @description `"accepted" | "rejected" | "judge-failed"` — present when completed. */
            verdict?: string | null;
        };
        /** @description `POST /api/submissions` body. */
        SubmitRequestDto: {
            language: string;
            path: string[];
            source: string;
        };
        SynapseIndexDto: {
            entries: components["schemas"]["CatalogEntryDto"][];
        };
        /**
         * @description One authored case: values per declared arg + the optional expected stdout. `sample` marks
         *     the browser-visible cases — the judge runs every case, but only samples cross the wire so a
         *     student cannot hard-code the hidden suite. Absent in `.tests.json` ⇒ `false` ⇒ hidden.
         */
        TestCase: {
            args: {
                [key: string]: string;
            };
            expected?: string | null;
            sample?: boolean;
        };
        /** @description The whole authored suite (a testcases fence or a `.tests.json` sidecar). */
        TestSpec: {
            args: components["schemas"]["ArgSpec"][];
            cases: components["schemas"]["TestCase"][];
        };
        /**
         * @description The whole conversation each turn — the server is stateless; the transcript lives in the
         *     client and dies with the page.
         */
        TutorChatRequestDto: {
            code?: string | null;
            language?: string | null;
            messages: components["schemas"]["ChatMessage"][];
            problemPath?: string | null;
        };
        TutorChatResponseDto: {
            content: string;
        };
        TutorConfigDto: {
            enabled: boolean;
            model: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listAllowlist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every grant, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllowlistEntryDto"][];
                };
            };
            /** @description Anonymous */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    grantAllowlist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrantRequestDto"];
            };
        };
        responses: {
            /** @description The stored grant */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllowlistEntryDto"];
                };
            };
            /** @description Blank username */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Anonymous */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    revokeAllowlist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The granted username */
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Anonymous */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No such grant */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listContentEditors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every grant, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllowlistEntryDto"][];
                };
            };
            /** @description Anonymous */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    grantContentEditor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrantRequestDto"];
            };
        };
        responses: {
            /** @description The stored grant */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllowlistEntryDto"];
                };
            };
            /** @description Blank username */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Anonymous */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    revokeContentEditor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The granted username */
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Anonymous */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No such grant */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listLessonViews: {
        parameters: {
            query?: {
                /** @description Rows to return (default 50, max 500) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Most-read lessons first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonViewDto"][];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Store failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getAuthConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Keycloak coordinates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthConfigDto"];
                };
            };
            /** @description The issuer is not a Keycloak realm URL */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listBlogPosts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every published post, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlogSummaryDto"][];
                };
            };
        };
    };
    getBlogPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The post's slug */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The post */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlogPostDto"];
                };
            };
            /** @description Unknown slug */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listMyEdits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's change requests */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditRequestDto"][];
                };
            };
            /** @description Anonymous */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not a content editor */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    proposeEdit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposeEditRequestDto"];
            };
        };
        responses: {
            /** @description The change request */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditRequestDto"];
                };
            };
            /** @description The proposed edit is not valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Anonymous */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not a content editor */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not an editable page */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The page changed while editing */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The content repository is unreachable */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getEditConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Editing coordinates for this caller */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditConfigDto"];
                };
            };
            /** @description The allowlist store failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getEditSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description category…/book/chapter…/lesson */
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The editable source */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditSourceDto"];
                };
            };
            /** @description Anonymous */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not a content editor */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not an editable page */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The verified caller */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDto"];
                };
            };
            /** @description Missing or invalid bearer */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Verifier unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    deleteMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Keycloak account is gone */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid bearer */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Keycloak admin API unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listProgress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's completed lesson paths */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressListDto"];
                };
            };
        };
    };
    markProgress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkProgressRequestDto"];
            };
        };
        responses: {
            /** @description Marked complete; the caller's completed paths */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressListDto"];
                };
            };
            /** @description Anonymous */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Store failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    resetProgress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Progress cleared */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResultDto"];
                };
            };
            /** @description Anonymous */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Store failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready to serve */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
            /** @description A backing store is unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    runCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description The run's outcome (including failed programs) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResult"];
                };
            };
            /** @description Bad bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Payload over the byte caps */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unknown language */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Over the run budget */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Backend failed */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Backend unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listSubmissions: {
        parameters: {
            query: {
                /** @description The lesson's directory-mirror path */
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's submissions, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionDto"][];
                };
            };
        };
    };
    submitSolution: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitRequestDto"];
            };
        };
        responses: {
            /** @description Stored; judging in background */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionAcceptedDto"];
                };
            };
            /** @description Not a problem */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Over the submission budget */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    eraseSubmissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Erased */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResultDto"];
                };
            };
            /** @description Anonymous */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The submission id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The submission */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionDto"];
                };
            };
            /** @description Not a submission id */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unknown submission */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    deleteSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The submission id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResultDto"];
                };
            };
            /** @description Anonymous */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Someone else's */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getComponentDoc: {
        parameters: {
            query: {
                /** @description The lesson's directory-mirror path */
                lesson: string;
            };
            header?: never;
            path: {
                /** @description LikeC4 element id (FQN or leaf) */
                element_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The component doc */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComponentDocDto"];
                };
            };
            /** @description No such doc */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getSynapseIndex: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SynapseIndexDto"];
                };
            };
            /** @description Index invalid / IO */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getSynapseLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description category…/book/chapter…/lesson */
                paths: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The lesson payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonPayloadDto"];
                };
            };
            /** @description No such lesson */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    tutorChat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TutorChatRequestDto"];
            };
        };
        responses: {
            /** @description The coach's reply */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TutorChatResponseDto"];
                };
            };
            /** @description The coach is off (the route is never mounted) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Backend failed */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Backend unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getTutorConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Whether the coach is on, and its model */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TutorConfigDto"];
                };
            };
        };
    };
}
